[default]
[default.local_start_api]
[default.local_start_api.parameters]
host = "127.0.0.1"
port = 3000
env_vars = "config/env.json"
docker_network = "lambda-network"

[default.local_start_lambda]
[default.local_start_lambda.parameters]
env_vars = "config/env.json"
docker_network = "lambda-network"

[default.local_invoke]
[default.local_invoke.parameters]
env_vars = "config/env.json"

[default.build]
[default.build.parameters]
use_container = true
cached = true
parallel = true
base_dir = "."
build_dir = ".aws-sam/build"
cache_dir = ".aws-sam/cache"
template_file = "template.yaml"
manifest = "requirements.txt"
metadata = "metadata.json"

[default.deploy]
[default.deploy.parameters]
stack_name = "lambda-monorepo"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []