AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda Monorepo - Simple SAM Template

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs20.x
    MemorySize: 256
    Environment:
      Variables:
        NODE_ENV: development
        LOG_LEVEL: info

Resources:
  # API Gateway
  Api:
    Type: AWS::Serverless::Api
    Properties:
      Name: "lambda-monorepo-api"
      StageName: dev
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  # Lambda Functions
  UserFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "user-service"
      CodeUri: services/user-service/dist/
      Handler: index.handler
      Events:
        UsersApi:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /users
            Method: ANY
        UsersProxyApi:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /users/{proxy+}
            Method: ANY

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${Api}.execute-api.${AWS::Region}.amazonaws.com/dev/"

  UserFunctionArn:
    Description: "User Lambda Function ARN"
    Value: !GetAtt UserFunction.Arn