AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: User Service Lambda Function

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, production]

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs20.x
    MemorySize: 256
    Environment:
      Variables:
        NODE_ENV: !Ref Environment
        AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

Resources:
  UserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: index.handler

Outputs:
  UserFunction:
    Description: 'User Lambda Function ARN'
    Value: !GetAtt UserFunction.Arn
  UserFunctionIamRole:
    Description: 'Implicit IAM Role created for User function'
    Value: !GetAtt UserFunctionRole.Arn
