AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: User Service Lambda Function

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, production]

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs20.x
    MemorySize: 256
    Environment:
      Variables:
        NODE_ENV: !Ref Environment
        AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

Resources:
  UserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: index.handler
      Events:
        CreateUser:
          Type: Api
          Properties:
            Path: /users
            Method: POST
        GetUsers:
          Type: Api
          Properties:
            Path: /users
            Method: GET
        GetUser:
          Type: Api
          Properties:
            Path: /users/{userId}
            Method: GET
        UpdateUser:
          Type: Api
          Properties:
            Path: /users/{userId}
            Method: PUT
        DeleteUser:
          Type: Api
          Properties:
            Path: /users/{userId}
            Method: DELETE
      Environment:
        Variables:
          USERS_TABLE: !Ref UsersTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${Environment}-users"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

Outputs:
  UserApi:
    Description: "API Gateway endpoint URL for User service"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/users/"
  UserFunction:
    Description: "User Lambda Function ARN"
    Value: !GetAtt UserFunction.Arn
  UserFunctionIamRole:
    Description: "Implicit IAM Role created for User function"
    Value: !GetAtt UserFunctionRole.Arn
  UsersTable:
    Description: "DynamoDB table for users"
    Value: !Ref UsersTable